controller_manager:
  ros__parameters:
    update_rate: 400 #  Hz

    forward_command_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController

    forward_command_controller_lead:
      type: forward_command_controller/MultiInterfaceForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

forward_command_controller_lead:
  ros__parameters:
    joint: 'leg_front_r_3'
    interface_names: ['effort', 'kp', 'kd']

forward_command_controller:
  ros__parameters:
    joint: 'leg_front_l_3'
    interface_names: ['effort', 'kp', 'kd']

joint_state_broadcaster:
  ros__parameters:
    joints:
      - leg_front_r_1
      - leg_front_r_2
      - leg_front_r_3
      - leg_front_l_1
      - leg_front_l_2
      - leg_front_l_3
      - leg_back_r_1
      - leg_back_r_2
      - leg_back_r_3
      - leg_back_l_1
      - leg_back_l_2
      - leg_back_l_3
    interface_name: position

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: base_link
    sensor_name: imu_sensor
